### ISSUE TITLE
Consulta sobre las tablas del paquete

### ISSUE THREAD

**Issue by pablo-87** [RichDeto/geouy#2]
Hola.

Primero, quiero agradecerte por el paquete elaborado, ya que tiene mucho potencial de ayuda para muchos.

Tengo una consulta para hacer acerca de las tablas. Hay manera de unirlas? Pienso que la variable "the_geom" podría cumplir esa función de pivote, pero no me queda claro.

Y como sería la vinculación entre los mapas (geouy) y la ECH?

Desde ya muchas gracias por el tiempo!
Saludos

**Comment by RichDeto** [comment]
Gracias Pablo, 

Efectivamente, estas funciones toman como pivote la geomatría, dado que se prioriza consumir las capas de los repositorios oficiales, en sí fue la causa de la función which_uy(), que toma como base sf::st_join() para hacer el enlace espacial entre tablas, quizás se puede agregar un `param` por si fuera del código y/o nombre de la otra tabla (como está ahora), te pegue todas las variables.

En cuanto a la combinación de geouy y ech, se podría decir que fue el origen de esta librería... ya que junto a @calcita habíamos empezado a hacer una libraría que conjugaba ambas cosas, y ahora dado que la pata de la  [ech](https://github.com/calcita/ech) viene tratando de alinearse mediante el repo holatam con las librerías EPH (Argentina) y CASEN (Chile) , la pata Geo la desarrollé por fuera, pero obviamente cuando salga ech van a ser más que compatibles... 

Cualquier otra consulta bienvenida sea...
Saludos
